baseURL: "https://sahidvelji.com/"
title: Sahid Velji
theme: PaperMod

enableRobotsTXT: true

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # enables opengraph, twitter-cards and schema
  description: "Sahid Velji's personal site"
  author: Sahid Velji
  images: ["sahid-velji.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  profileMode:
    enabled: true
    title: Sahid Velji
    imageUrl: "sahid-velji.png"
    imageWidth: 250
    imageHeight: 250
    imageTitle: Sahid Velji

  socialIcons:
    - name: linkedin
      url: "https://linkedin.com/in/sahidvelji"
    - name: github
      url: "https://github.com/sahidvelji"
    - name: kaggle
      url: "https://kaggle.com/sahidvelji"
    - name: x
      url: "https://x.com/sahidvelji"

markup:
  highlight:
    noClasses: false
